/**
 * JustPDFCraft AI Service
 * 
 * Modular client-side connector for Google Gemini & OpenAI.
 * Strict Constraint: Zero fake AI output. Uses real client-side fetch when
 * configured by the user, and gracefully handles unconfigured state.
 */

export type AIProvider = 'gemini' | 'openai';

export interface AIConfig {
  provider: AIProvider;
  geminiApiKey: string;
  openaiApiKey: string;
  customModel?: string;
}

const STORAGE_KEY = 'justpdfcraft_ai_config';

export const getAIConfig = (): AIConfig => {
  if (typeof window === 'undefined') {
    return { provider: 'gemini', geminiApiKey: '', openaiApiKey: '' };
  }
  try {
    const raw = localStorage.getItem(STORAGE_KEY) || localStorage.getItem('swifteditoo_ai_config');
    if (raw) return JSON.parse(raw);
  } catch {}
  return { provider: 'gemini', geminiApiKey: '', openaiApiKey: '' };
};

export const saveAIConfig = (config: AIConfig): void => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(config));
  } catch {}
};

export const isAIConfigured = (): boolean => {
  const config = getAIConfig();
  if (config.provider === 'gemini') {
    return Boolean(config.geminiApiKey && config.geminiApiKey.trim().length > 5);
  }
  if (config.provider === 'openai') {
    return Boolean(config.openaiApiKey && config.openaiApiKey.trim().length > 5);
  }
  return false;
};

export class AIService {
  public static async generateResponse(prompt: string, context?: string): Promise<string> {
    const config = getAIConfig();

    if (config.provider === 'gemini') {
      return this.callGemini(config.geminiApiKey, prompt, context, config.customModel);
    } else {
      return this.callOpenAI(config.openaiApiKey, prompt, context, config.customModel);
    }
  }

  private static async callGemini(
    apiKey: string,
    prompt: string,
    context?: string,
    customModel?: string
  ): Promise<string> {
    if (!apiKey || apiKey.trim().length === 0) {
      throw new Error('Google Gemini API Key is not configured. Please add your key in AI Settings.');
    }

    const model = customModel || 'gemini-1.5-flash';
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey.trim()}`;

    const contents: any[] = [];
    if (context && context.trim()) {
      contents.push({
        role: 'user',
        parts: [{ text: `DOCUMENT CONTEXT / STUDY MATERIAL:\n"""\n${context.slice(0, 30000)}\n"""` }],
      });
      contents.push({
        role: 'model',
        parts: [{ text: 'Understood. I have read the document context and am ready to answer or process your request based on it.' }],
      });
    }

    contents.push({
      role: 'user',
      parts: [{ text: prompt }],
    });

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents,
        generationConfig: {
          temperature: 0.4,
          maxOutputTokens: 2048,
        },
      }),
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const msg = errData?.error?.message || `Gemini API error (Status ${response.status})`;
      throw new Error(msg);
    }

    const data = await response.json();
    const candidate = data.candidates?.[0];
    const text = candidate?.content?.parts?.[0]?.text;

    if (!text) {
      throw new Error('No text generated by Gemini. Please try again.');
    }

    return text;
  }

  private static async callOpenAI(
    apiKey: string,
    prompt: string,
    context?: string,
    customModel?: string
  ): Promise<string> {
    if (!apiKey || apiKey.trim().length === 0) {
      throw new Error('OpenAI API Key is not configured. Please add your key in AI Settings.');
    }

    const model = customModel || 'gpt-4o-mini';
    const url = 'https://api.openai.com/v1/chat/completions';

    const messages: any[] = [
      {
        role: 'system',
        content: 'You are JustPDFCraft AI, an intelligent, concise, and accurate study assistant for students and professionals. Format output cleanly in Markdown.',
      },
    ];

    if (context && context.trim()) {
      messages.push({
        role: 'system',
        content: `Study Material / Document Context:\n"""\n${context.slice(0, 30000)}\n"""`,
      });
    }

    messages.push({
      role: 'user',
      content: prompt,
    });

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey.trim()}`,
      },
      body: JSON.stringify({
        model,
        messages,
        temperature: 0.4,
      }),
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const msg = errData?.error?.message || `OpenAI API error (Status ${response.status})`;
      throw new Error(msg);
    }

    const data = await response.json();
    const text = data.choices?.[0]?.message?.content;

    if (!text) {
      throw new Error('No response returned from OpenAI.');
    }

    return text;
  }
}
